[package]
name = "rgx"
version = "0.1.0"
authors = ["Alexis Sellier <alexis@cloudhead.io>"]
license = "MIT"
edition = "2018"
keywords = ["graphics", "gamedev"]

[lib]
name = "rgx"

[dependencies.wgpu]
git = "https://github.com/gfx-rs/wgpu-rs.git"
rev = "44ce0875f1cb339c802f9233e10e4ba42ee97bd1"
version = "*"
features = ["vulkan"]

[dependencies]
env_logger = "*"
shaderc = "*"
cgmath = "*"

[dev-dependencies]
image = "*"
